# Generated by Django 4.2.7 on 2024-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='tnved',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Код тн вэд'),
        ),
    ]
