# Generated by Django 4.2.7 on 2024-06-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_categories_tnved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='tnved',
            field=models.CharField(max_length=150, null=True, verbose_name='Код тн вэд'),
        ),
    ]
