# Generated by Django 4.2.7 on 2024-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_tnved'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Дата добавления', null=True),
        ),
    ]
