# Generated by Django 4.2.7 on 2024-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_color_options_alter_consist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название')),
            ],
            options={
                'verbose_name': 'Строна производства',
                'verbose_name_plural': 'Строна производства',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='filter_consist',
            field=models.BooleanField(default=True, verbose_name='Нужен фильтр для составов'),
        ),
        migrations.AddField(
            model_name='categories',
            name='filter_size',
            field=models.BooleanField(default=True, verbose_name='Нужен фильтр для размеров'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'РОССИЯ'), (2, 'МЕЖДУНАРОДНЫЙ')], default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.ManyToManyField(related_name='country', to='goods.country'),
        ),
    ]
