# Generated by Django 4.2.7 on 2024-06-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_products_category_remove_products_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.country', verbose_name='Страна производства'),
        ),
    ]
