# Generated by Django 4.2.7 on 2024-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(max_length=150, verbose_name='Название'),
        ),
    ]
