# Generated by Django 4.2.7 on 2024-06-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('-id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
